[project]
name = "OpenStudioLandscapes-Syncthing"
description = "Syncthing Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-Syncthing"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-Syncthing[graphviz]",
]
nox = [
    "OpenStudioLandscapes-Syncthing[testing]",
]
dev = [
    "OpenStudioLandscapes-Syncthing[testing]",
    "OpenStudioLandscapes-Syncthing[lint]",
    "OpenStudioLandscapes-Syncthing[nox]",
    "OpenStudioLandscapes-Syncthing[sbom]",
    "OpenStudioLandscapes-Syncthing[coverage]",
    "OpenStudioLandscapes-Syncthing[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.Syncthing"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.Syncthing.definitions"
code_location_name = "OpenStudioLandscapes-Syncthing"
